# Generated by Django 3.1.7 on 2021-03-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='anser_text',
            field=models.CharField(default='aiueo', max_length=400),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Anser',
        ),
    ]
